### ISSUE TITLE
aire de santa fe

### ISSUE THREAD

**Issue by c4p1t4nn** [abskmj/iptv-youtube-live#11]
### Channel Name

aire de santa fe

### Source Link

https://www.youtube.com/watch?v=XU-wkl6g-I4

### Language

español

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist.

**Comment by abskmj** [comment]
The channel does not have any live videos.
