### ISSUE TITLE
Christus Vincit TV 

### ISSUE THREAD

**Issue by Remek33** [abskmj/iptv-youtube-live#18]
### Channel Name

Christus Vincit TV 

### Source Link

https://www.youtube.com/@tv-christusvincit/streams

###Logo Link 
https://regnumchristi.com.pl/images/regnumchisti.jpg

### Language

Polish

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have checked that the source does not already exist.

**Comment by Remek33** [comment]
Could you please add a logo to the Christus Vincit TV channel:

https://regnumchristi.com.pl/images/regnumchisti.jpg

**Comment by abskmj** [comment]
The name and logo for the channel is automatically added / updated by the script from the YouTube channel page. I can't update them.
