### ISSUE TITLE
ythls-v2.onrender.com shows Error

### ISSUE THREAD

**Issue by debmagic** [abskmj/iptv-youtube-live#23]
### Source information

https://ythls-v2.onrender.com

### Steps to reproduce

Open your website: https://ythls-v2.onrender.com
The following error displays: Cannot GET /

### IPTV Provider

N/A

### Other details

Love this service. Is your website down or service stopped?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by abskmj** [comment]
The service is currently unstable because of high volume of requests in a short span of time. It might take some time before the service is stable again.
