### ISSUE TITLE
live video m3u8

### ISSUE THREAD

**Issue by cxzhsjajdjkqjdjxkqf** [abskmj/iptv-youtube-live#25]
### Channel Name

brillian

### Source Link

https://www.youtube.com/live/-7lJuKnEHfA?si=jcwSo3s9yQiUKnCN

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist.

**Comment by cxzhsjajdjkqjdjxkqf** [comment]
m3u8

**Comment by abskmj** [comment]
channel is not live for past 2 months
