### ISSUE TITLE
Please add this channel

### ISSUE THREAD

**Issue by uncannyshop** [abskmj/iptv-youtube-live#30]
Please add these channels

https://youtube.com/@abscbnentertainment/live

https://youtube.com/c/gmanetwork/live

**Comment by abskmj** [comment]
Both of the channels are already added. Are you not seeing them in the list?

**Comment by uncannyshop** [comment]
they are not working. tried them both

**Comment by abskmj** [comment]
It could be the server. Currently it is hosted on a basic tier of the cloud provider. It sometimes stops working due to high traffic.

**Comment by uncannyshop** [comment]
oh ok thats why it doesnt work sometimes.
