### ISSUE TITLE
For a Youtube Channel with single live doesn't work sometimes

### ISSUE THREAD

**Issue by scstvlive** [abskmj/iptv-youtube-live#33]
Channel: https://www.youtube.com/@RtvNews
https://ythls-v3.onrender.com/channel/UC2P5Fd5g41Gtdqf0Uzh8Qaw.m3u8

Channel: https://www.youtube.com/@NEWS24TV
https://ythls-v3.onrender.com/channel/UCPREnbhKQP-hsVfsfKP-mCw.m3u8

error: stream url not found

**Comment by scstvlive** [comment]
Your https://ythls-v3.onrender.com/channel/UCUvXoiDEKI8VZJrr58g4VAw.m3u8 is not working for most of the channels

**Comment by abskmj** [comment]
Now it should be working
