### ISSUE TITLE
No youtube live channel is working

### ISSUE THREAD

**Issue by scstvlive** [abskmj/iptv-youtube-live#35]
### Source information

DBC NEWS etc

### Steps to reproduce

For last few days nothing is working. Getting the following error:
For channel:
{"message":"stream url not found"}

For video:
{"message":"Youtube HLS Server is running, details on how to use it at https://github.com/abskmj/iptv-youtube-live"}

Using domain mentioned here : https://github.com/abskmj/youtube-hls-m3u8

Can you please check?
Thanks!

### IPTV Provider

Youtube

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by abskmj** [comment]
Now it should be working
