### ISSUE TITLE
Error message with manual livestream converting

### ISSUE THREAD

**Issue by haworthia-hime** [abskmj/iptv-youtube-live#37]
### Source information

N / A

### Steps to reproduce

1. Find livestream, in my case I'm looking to create an m3u from [this video](https://www.youtube.com/watch?v=iBsN7Y_eOBQ)?
2. Use the onrender link format for live videos (https://ythls-v3.onrender.com/video/$youtube_video_id.m3u8), so https://ythls-v3.onrender.com/video/iBsN7Y_eOBQ.m3u8
3. Find that there is an error message, `Youtube HLS Server is running, details on how to use it at https://github.com/abskmj/iptv-youtube-live`.

### IPTV Provider

N / A

### Other details

My biggest apologies if this is simply user error, I have tested on a VPN and with a different browser as well as looking through the issues, and only found one other one similar #35. Thank you for your hard work!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by abskmj** [comment]
Video endpoints are disabled on public server to reduce the number of requests. use channel id instead
