### ISSUE TITLE
PAKA PAKA

### ISSUE THREAD

**Issue by pasiondelhincha** [abskmj/iptv-youtube-live#7]
### Channel Name

PAKA PAKA ARGENTINA

### Source Link

https://www.youtube.com/watch?v=w0vRtnGORhg&ab_channel=Pakapaka

### Language

SPANISH

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist.

**Comment by abskmj** [comment]
Channel doesn't seem to be live most of the time.
